// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjShQZzCk4qK4h5H8iXancYZSwRQzMzu4',
    appId: '1:581781960241:web:eb76eb6c28ae6428970710',
    messagingSenderId: '581781960241',
    projectId: 'attendance-portal-845c3',
    authDomain: 'attendance-portal-845c3.firebaseapp.com',
    storageBucket: 'attendance-portal-845c3.appspot.com',
    measurementId: 'G-ND6NPBRBQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoWvOD7vDhCneoJhmC_dE_tGfiCbYaGoQ',
    appId: '1:581781960241:android:782635cfbeec54e0970710',
    messagingSenderId: '581781960241',
    projectId: 'attendance-portal-845c3',
    storageBucket: 'attendance-portal-845c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCE1SWs4wpQCd3x9XA3VHYTfSt90SFnvM',
    appId: '1:581781960241:ios:e6c9b25aeded642d970710',
    messagingSenderId: '581781960241',
    projectId: 'attendance-portal-845c3',
    storageBucket: 'attendance-portal-845c3.appspot.com',
    androidClientId: '581781960241-ipcbiuigij4skd7tvi2rin8kcq2jf340.apps.googleusercontent.com',
    iosClientId: '581781960241-3fc6ggjuntmur9itiqtvo2tm2trfesl0.apps.googleusercontent.com',
    iosBundleId: 'com.example.geofencingBasedAttendanceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCE1SWs4wpQCd3x9XA3VHYTfSt90SFnvM',
    appId: '1:581781960241:ios:0a14accc02a5ccbb970710',
    messagingSenderId: '581781960241',
    projectId: 'attendance-portal-845c3',
    storageBucket: 'attendance-portal-845c3.appspot.com',
    androidClientId: '581781960241-ipcbiuigij4skd7tvi2rin8kcq2jf340.apps.googleusercontent.com',
    iosClientId: '581781960241-p3nk2s9tl0m3qlevjuvc1uakjcanpbkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.geofencingBasedAttendanceSystem.RunnerTests',
  );
}
